export const PARSE_TRANSACTIONS_PROGRESS =  'PARSE_TRANSACTIONS_PROGRESS';
export const PARSE_TRANSACTIONS_SUCCESS  =  'PARSE_TRANSACTIONS_SUCCESS';
export const PARSE_TRANSACTIONS_FAILURE =   'PARSE_TRANSACTIONS_FAILURE';

export const SUBMIT_TRANSACTIONS_PROGRESS =  'SUBMIT_TRANSACTIONS_PROGRESS';
export const SUBMIT_TRANSACTIONS_SUCCESS  =  'SUBMIT_TRANSACTIONS_SUCCESS';
export const SUBMIT_TRANSACTIONS_FAILURE =   'SUBMIT_TRANSACTIONS_FAILURE';


export const DUPLICATE_TRANSACTIONS_PROGRESS =  'DUPLICATE_TRANSACTIONS_PROGRESS';
export const DUPLICATE_TRANSACTIONS_SUCCESS  =  'DUPLICATE_TRANSACTIONS_SUCCESS';
export const DUPLICATE_TRANSACTIONS_FAILURE =   'DUPLICATE_TRANSACTIONS_FAILURE';


export const FETCH_TRANSACTIONS_PROGRESS =  'FETCH_TRANSACTIONS_PROGRESS';
export const FETCH_TRANSACTIONS_SUCCESS  =  'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE =   'FETCH_TRANSACTIONS_FAILURE';